### ISSUE TITLE
release 0.24 renamed module to scapy3k

### ISSUE THREAD

**Issue by dajose** [phaethon/kamene#246]
Hi, I'm not very familiar with the renaming schema you guys are doing... but I'm confused with the transition naming change on latest 0.24 release to scapy3k.

what's the intention there? also, The git tag for that release doesn't match the code that is downloadable on pypi.

**Comment by dajose** [comment]
oh, but I think v0.24 would not work as you intended, as the name of the module was changed to scapy3k. So, it will not give a warning but fail at import.

**Comment by phaethon** [comment]
The package file on PyPI had an issue, just fixed it. If using scapy-python3 PyPI (v0.25 latest) then import scapy... should work, when using kamene from PyPI, then import kamene... should work. 
Anyway, the whole intent of updating scapy-python3 package was just to add notification message, it is not going to be updated.

**Comment by dajose** [comment]
:) that's what we needed here. Thanks :)

We'll update to kamane in the future
