### ISSUE TITLE
help required

### ISSUE THREAD

**Issue by radharani1306** [phaethon/kamene#253]
I am newbie to Kamene,scapy. Could you please provide me some examples, so that I can develop my skills on these technologies

**Comment by phaethon** [comment]
Dear @radharani1306 , it is great that you want to learn kamene. You can see initial guidance on documentation page https://kamene.readthedocs.io/en/latest/ . If you want a more personalised assistance, it would be great if you contribute back to the project in one form or another. One way would be coming up with additional ideas for examples in the documentation.

**Comment by radharani1306** [comment]
thanks for reply. please consider to include more examples in documemt
which will be helpful for newbies like me as well as for your project
growthwise
