### ISSUE TITLE
compatibility with Anaconda

### ISSUE THREAD

**Issue by radharani1306** [phaethon/kamene#254]
I am using Pycharm with Anaconda environment.  I installed as per your guidelines in kali linux. I am able to see "Kamene" with conda list" command, but when I use "import kamene" in my pycharm I am getting error that no modue error, Please guide me how can I install kamene  to use it in my pycharm

**Comment by phaethon** [comment]
Can you provide more info how exactly you did install kamene? 
Did you install it using pip? If yes, did you use pip from the Anaconda environment (you may have multiple python environments)?

**Comment by radharani1306** [comment]
1) First installed  Linux libpcap using following command

git clone https://github.com/the-tcpdump-group/tcpdump.git

2) Installed Kamene

>>git clone https://github.com/phaethon/kamene.git3/
>> /home/ram/anaconda3/bin/python3 setup.py install

Please refer below screen shots

Which command Screen shot

[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by phaethon** [comment]
So if you run `/home/ram/anaconda3/bin/python3 `, and when you get the python shell and write `import kamene`, what do you get?

**Comment by radharani1306** [comment]
I am getting the following error

[image: temp.png]

**Comment by phaethon** [comment]
I cannot see the image, it seems to be stripped. Can you paste the message in text?

**Comment by phaethon** [comment]
You are getting "Unresolved reference 'kamene'" after running `import kamene`? This does not sound possible. Python does not generate such message upon running `import` statement normally. Please, explain in more detail how you get it.

**Comment by radharani1306** [comment]
please check the attached video

**Comment by phaethon** [comment]
Video attachments are, also, stripped from GitHub it seems. Please, check yourself logging into web interface of GitHub to see that there is no video.

**Comment by radharani1306** [comment]
Please check it now

[Screencast_09-12-2018.zip](https://github.com/phaethon/kamene/files/2379161/Screencast_09-12-2018.zip)

**Comment by phaethon** [comment]
You have multiple python envs. It seems you use the one in ...anaconda3/envs/Networking/... when running PyCharm. Depending on how you created the environment the library installed by conda package might not be available. 
Can you run from the shell (!) python interpreter using shell path from `which python`:
`/home/ram/anaconda3/bin/python3`

Then inside the prompt which will appear in the shell run:
`import kamene`

Then do the same, but use Networking env path:
`~/anaconda3/envs/Networking/bin/python`
and again inside this shell:
`import kamene`

**Comment by radharani1306** [comment]
I have executed the commands as per your guidance, please refer the attached screen shots
![capture2](https://user-images.githubusercontent.com/42796132/45489810-ffcc2300-b782-11e8-9653-e32bb3015db0.JPG)
![capture1](https://user-images.githubusercontent.com/42796132/45489811-0064b980-b783-11e8-8ccb-ec2c3a11d668.JPG)

**Comment by phaethon** [comment]
The good thing is that now I see your screenshots :)
Apparently kamene is not successfully installed as it says "No module named 'kamene'. I have no idea who created package for Anaconda, but you as you have linux you can simply install kamene using pip.
Do `pip3 install kamene` from the shell. Which pip3 you use (from anaconda3/bin or envs/Networking/bin/python) will determine in which environment will kamene be available.

The other note - I asked you to `import kamene` just to check if module is present. To actually use it in the way it is usually used (and to copy samples from documentation) you need to do `from kamene.all import *`

**Comment by radharani1306** [comment]
In order to install (pip3 install kamene) as per you, I tried to uninstall the existing "Kamene" but getting error. Please refer the screen shot for error information

> **Note:**
> 1) First installed  Linux libpcap using following command
> 
> git clone https://github.com/the-tcpdump-group/tcpdump.git
> 
> 2) Installed Kamene
> >git clone https://github.com/phaethon/kamene.git3/
> > /home/ram/anaconda3/bin/python3 setup.py install

![capture](https://user-images.githubusercontent.com/42796132/45502707-4f6e1700-b7a2-11e8-80bb-deeaf9f62a1a.JPG)

**Comment by phaethon** [comment]
Ignore the warning message. Did you proceed with the install?

**Comment by radharani1306** [comment]
I am unable to install using pip3 from /home/ram/anaconda3/bin
and there is no pip3 in ~/anaconda3/envs/Networking/bin/

![capture](https://user-images.githubusercontent.com/42796132/45548612-99a6d500-b842-11e8-9511-ead41b41b0b4.JPG)
