### ISSUE TITLE
help required

### ISSUE THREAD

**Issue by radharani1306** [phaethon/kamene#256]
1) I have installed kamene using "pip3 install kamene"
2) issued command from shell "sudo kamene"
3) executed the following command in kamene shell
           from kamene import *
           p = IP(dst = 'www.google.com') / TCP(dport = 80) / Raw(b'Some raw bytes')
           # to see packet content as bytes use bytes(p) not str(p)
          sr1(p)
4) The above code executed fine and able to send 1 packet.
5) I save the above code in test.py file and tried to execute using "python3 test.py", I am getting the following error
            Traceback (most recent call last):
                   File "test.py", line 2, in <module>
              p = IP(dst = 'www.google.com') / TCP(dport = 80) / Raw(b'Some raw bytes')
              NameError: name 'IP' is not defined

Please refer the attached screen shot and help me what wrong with my setup
![capture](https://user-images.githubusercontent.com/42796132/45663744-a0c13200-bb25-11e8-91e3-33f30d1dfd2c.JPG)

**Comment by radharani1306** [comment]
please help me

**Comment by phaethon** [comment]
I, actually, wrote it to you earlier. You have to use `from kamene.all import *` in order to use it in this way. Notice `.all`

**Comment by phaethon** [comment]
Is `python` executing python3 (or python2)?
Assuming yes, is it executing the same environment where you installed kamene?

**Comment by radharani1306** [comment]
it's my fault, I supposed to use "python3" rather than "python"

![image](https://user-images.githubusercontent.com/42796132/45792955-95990e00-bcad-11e8-8fe3-b6550479835a.png)

**Comment by phaethon** [comment]
You owe me popularizing kamene among 10 of your fellow students/coworkers for debugging such type of an issue ;)

**Comment by radharani1306** [comment]
:) Thanks for your long support
