### ISSUE TITLE
HTTP Layer

### ISSUE THREAD

**Issue by f0lg0** [phaethon/kamene#263]
I am unable to see the HTTP layer with packet.show(), I am using python3. Is there support for HTTP layers in Kamene (python3)? Like scapy_http

```

**Comment by phaethon** [comment]
Of course there is a support for HTTP layer. Without further information, though, I cannot comment why you are not able to dissect properly.

**Comment by f0lg0** [comment]
More details here (my question)
https://stackoverflow.com/questions/60694408/packet-sniffing-http-layer-in-kamene-scapy-for-python3

Thanks!
